"""empty message

Revision ID: f118e77c4a7f
Revises: 
Create Date: 2019-11-15 21:41:26.169491

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f118e77c4a7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ip')
    op.drop_index('ix_user1_username', table_name='user1')
    op.drop_table('user1')
    op.add_column('info', sa.Column('belonging', sa.String(length=20), nullable=True))
    op.add_column('info', sa.Column('city', sa.String(length=20), nullable=True))
    op.add_column('info', sa.Column('level', sa.String(length=20), nullable=True))
    op.add_column('info', sa.Column('province', sa.String(length=20), nullable=True))
    op.add_column('info', sa.Column('unit_type', sa.Integer(), nullable=True))
    op.add_column('status', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('status', sa.Column('bandwith', sa.Integer(), nullable=True))
    op.add_column('status', sa.Column('firewall', sa.Boolean(), nullable=True))
    op.add_column('status', sa.Column('flow', sa.Integer(), nullable=True))
    op.add_column('status', sa.Column('has_cdn', sa.Boolean(), nullable=True))
    op.add_column('status', sa.Column('server', sa.String(length=100), nullable=True))
    op.add_column('status', sa.Column('server_ver', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('status', 'server_ver')
    op.drop_column('status', 'server')
    op.drop_column('status', 'has_cdn')
    op.drop_column('status', 'flow')
    op.drop_column('status', 'firewall')
    op.drop_column('status', 'bandwith')
    op.drop_column('status', 'active')
    op.drop_column('info', 'unit_type')
    op.drop_column('info', 'province')
    op.drop_column('info', 'level')
    op.drop_column('info', 'city')
    op.drop_column('info', 'belonging')
    op.create_table('user1',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user1_pkey')
    )
    op.create_index('ix_user1_username', 'user1', ['username'], unique=True)
    op.create_table('ip',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('unit', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('address_begin', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('address_end', postgresql.INET(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ip_pkey')
    )
    # ### end Alembic commands ###
